import React, { useMemo, useState } from 'react';
import { View, TextInput } from 'react-native';
import StatusChips from '@/components/filters/StatusChips';
import VendorPicker from '@/components/filters/VendorPicker';
import TextDateInput from '@/components/filters/TextDateInput';
import Button from '@/components/ui/Button';
import { useTheme } from '@/providers/ThemeProvider';
import type { OrderHistoryFilters } from '@/features/orders/history.types';
export default function OrderFilters({ initial, onApply }: { initial?: OrderHistoryFilters; onApply: (filters: OrderHistoryFilters) => void; }) { const { spacing, colors, radii } = useTheme(); const [status, setStatus] = useState(initial?.status ?? null); const [vendorId, setVendor] = useState<number | null>(initial?.vendorId ?? null); const [fromDate, setFromDate] = useState<string | null>(initial?.fromDate ?? null); const [toDate, setToDate] = useState<string | null>(initial?.toDate ?? null); const [query, setQuery] = useState<string | null>(initial?.query ?? null); const inputStyle = { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radii.md, color: colors.text, flex: 1 }; const filters = useMemo<OrderHistoryFilters>(() => ({ status, vendorId, fromDate, toDate, query }), [status, vendorId, fromDate, toDate, query]); return (<View style={{ gap: spacing.sm }}><StatusChips value={status} onChange={setStatus} /><VendorPicker value={vendorId} onChange={setVendor} /><View style={{ flexDirection: 'row', gap: spacing.sm }}><TextDateInput label="From" value={fromDate || ''} onChange={setFromDate} /><TextDateInput label="To" value={toDate || ''} onChange={setToDate} /></View><TextInput placeholder="Search by # or vendor" placeholderTextColor={colors.textMuted} value={query || ''} onChangeText={(t) => setQuery(t)} style={inputStyle} /><Button title="Apply filters" onPress={() => onApply(filters)} /></View>); }
